// Sounds the admin can pick for new-booking push notifications (Settings tab).
//
// Android 8+ fixes a notification channel's sound when the channel is
// created, so every sound gets its own channel (`bookings_<id>`), the app
// creates all of them, and the server posts to the one matching
// barber_profile.notification_sound. The custom sounds live in the APK's
// res/raw and, for in-browser previews, in public/sounds — both generated by
// scripts/generate-notification-sounds.mjs.

export const NOTIFICATION_SOUNDS = [
  { id: 'default',  label: 'ئاوازی سیستەم',  description: 'دەنگی بنەڕەتی ئاگادارکردنەوەی مۆبایلەکە' },
  { id: 'chime',    label: 'زەنگۆڵە',         description: 'دوو نۆتی نەرم و ئارام' },
  { id: 'bell',     label: 'زەنگ',            description: 'یەک لێدانی زەنگی ڕوون' },
  { id: 'doorbell', label: 'زەنگی دەرگا',     description: 'دینگ-دۆنگی ناسراو' },
  { id: 'alert',    label: 'ئاگاداری بەهێز',  description: 'ئاوازێکی خێرا و بەرز بۆ کاتی قەرەباڵغی' },
] as const;

export type NotificationSoundId = (typeof NOTIFICATION_SOUNDS)[number]['id'];

export const DEFAULT_NOTIFICATION_SOUND: NotificationSoundId = 'default';

export function isNotificationSound(v: unknown): v is NotificationSoundId {
  return NOTIFICATION_SOUNDS.some((s) => s.id === v);
}

export function soundChannelId(id: NotificationSoundId): string {
  return `bookings_${id}`;
}

// res/raw resource name — null for the phone's own default sound
export function soundResource(id: NotificationSoundId): string | null {
  return id === 'default' ? null : `notify_${id}`;
}

export function soundPreviewUrl(id: NotificationSoundId): string | null {
  const res = soundResource(id);
  return res ? `/sounds/${res}.wav` : null;
}
